TEAMS = [
    "ANA", "BOS", "BUF", "CGY", "CAR", "CHI", "COL", "CBJ",
    "DAL", "DET", "EDM", "FLA", "LAK", "MIN", "MTL", "NSH",
    "NJD", "NYI", "NYR", "OTT", "PHI", "PIT", "SEA", "SJS",
    "STL", "TBL", "TOR", "UTA", "VAN", "VGK", "WSH", "WPG",
]

TEAM_INFO = {
    "ANA": {"conference": "West", "division": "Pacific"},
    "BOS": {"conference": "East", "division": "Atlantic"},
    "BUF": {"conference": "East", "division": "Atlantic"},
    "CGY": {"conference": "West", "division": "Pacific"},
    "CAR": {"conference": "East", "division": "Metropolitan"},
    "CHI": {"conference": "West", "division": "Central"},
    "COL": {"conference": "West", "division": "Central"},
    "CBJ": {"conference": "East", "division": "Metropolitan"},
    "DAL": {"conference": "West", "division": "Central"},
    "DET": {"conference": "East", "division": "Atlantic"},
    "EDM": {"conference": "West", "division": "Pacific"},
    "FLA": {"conference": "East", "division": "Atlantic"},
    "LAK": {"conference": "West", "division": "Pacific"},
    "MIN": {"conference": "West", "division": "Central"},
    "MTL": {"conference": "East", "division": "Atlantic"},
    "NSH": {"conference": "West", "division": "Central"},
    "NJD": {"conference": "East", "division": "Metropolitan"},
    "NYI": {"conference": "East", "division": "Metropolitan"},
    "NYR": {"conference": "East", "division": "Metropolitan"},
    "OTT": {"conference": "East", "division": "Atlantic"},
    "PHI": {"conference": "East", "division": "Metropolitan"},
    "PIT": {"conference": "East", "division": "Metropolitan"},
    "SEA": {"conference": "West", "division": "Pacific"},
    "SJS": {"conference": "West", "division": "Pacific"},
    "STL": {"conference": "West", "division": "Central"},
    "TBL": {"conference": "East", "division": "Atlantic"},
    "TOR": {"conference": "East", "division": "Atlantic"},
    "UTA": {"conference": "West", "division": "Central"},
    "VAN": {"conference": "West", "division": "Pacific"},
    "VGK": {"conference": "West", "division": "Pacific"},
    "WSH": {"conference": "East", "division": "Metropolitan"},
    "WPG": {"conference": "West", "division": "Central"},
}
